import type { FeedbackStore } from "../../application/feedback-store.js";
import type { FeedbackRecord } from "../../domain/feedback.js";
import type { Pool } from "pg";
type Row = { feedback_id: string; employee_id: string; thread_id: string; target_message_id: string; rating: FeedbackRecord["rating"]; source: FeedbackRecord["source"]; created_at: Date; updated_at: Date };
const record = (row: Row): FeedbackRecord => ({ id: row.feedback_id, employeeId: row.employee_id, threadId: row.thread_id, targetMessageId: row.target_message_id, rating: row.rating, source: row.source, createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString() });
export function createPostgresFeedbackStore(pool: Pool): FeedbackStore { return {
  async saveFeedback(input) { const result = await pool.query<Row>("INSERT INTO minutka_private.feedback(feedback_id,employee_id,thread_id,target_message_id,rating,source,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$7) ON CONFLICT (employee_id,thread_id,target_message_id) DO UPDATE SET rating=EXCLUDED.rating, source=EXCLUDED.source, updated_at=EXCLUDED.updated_at RETURNING *", [input.id,input.employeeId,input.threadId,input.targetMessageId,input.rating,input.source,input.updatedAt]); return record(result.rows[0]); },
  async getFeedbackByTarget(input) { const result = await pool.query<Row>("SELECT * FROM minutka_private.feedback WHERE employee_id=$1 AND thread_id=$2 AND target_message_id=$3", [input.employeeId,input.threadId,input.targetMessageId]); return result.rows[0] ? record(result.rows[0]) : undefined; },
  async listFeedback(input) { const clauses: string[] = []; const params: Array<string | number> = []; if (input?.employeeId) { params.push(input.employeeId); clauses.push(`employee_id = $${params.length}`); } if (input?.threadId) { params.push(input.threadId); clauses.push(`thread_id = $${params.length}`); } if (input?.targetMessageId) { params.push(input.targetMessageId); clauses.push(`target_message_id = $${params.length}`); } const limit = Math.max(0, input?.limit ?? 10_000); params.push(limit); const result = await pool.query<Row>(`SELECT * FROM (SELECT * FROM minutka_private.feedback${clauses.length ? ` WHERE ${clauses.join(" AND ")}` : ""} ORDER BY created_at DESC LIMIT $${params.length}) recent ORDER BY created_at ASC`, params); return result.rows.map(record); },
}; }
