import type { TelegramSessionStore } from "../../telegram/telegram-session-store.js";
import { PersistenceError } from "../../application/persistence-error.js";
import type { Pool } from "pg";
import { keyedDigest } from "./digests.js";
type Row = { employee_id: string; thread_id: string; consent_accepted_at: Date | null; created_at: Date; updated_at: Date };
const session = (row: Row) => ({ employeeId: row.employee_id, threadId: row.thread_id, ...(row.consent_accepted_at ? { consentAcceptedAt: row.consent_accepted_at.toISOString() } : {}), createdAt: row.created_at.toISOString(), updatedAt: row.updated_at.toISOString() });
export function createPostgresTelegramSessionStore(pool: Pool, pepper: string): TelegramSessionStore { return {
  async getByIdentity(identity) { const result = await pool.query<Row>("SELECT employee_id,thread_id,consent_accepted_at,created_at,updated_at FROM minutka_private.telegram_sessions WHERE chat_id_digest=$1 AND (user_id_digest IS NOT DISTINCT FROM $2)", [keyedDigest(identity.chatId,pepper),identity.userId ? keyedDigest(identity.userId,pepper) : null]); return result.rows[0] ? session(result.rows[0]) : undefined; },
  async claim({ identity, session: next }) { const chat = keyedDigest(identity.chatId,pepper); const user = identity.userId ? keyedDigest(identity.userId,pepper) : null; const client = await pool.connect(); try { await client.query("BEGIN"); const existingChat = await client.query("SELECT 1 FROM minutka_private.telegram_sessions WHERE chat_id_digest=$1 FOR UPDATE", [chat]); if (existingChat.rowCount) { await client.query("ROLLBACK"); return { status: "chat_already_linked" as const }; } const existingEmployee = await client.query("SELECT 1 FROM minutka_private.telegram_sessions WHERE employee_id=$1 FOR UPDATE", [next.employeeId]); if (existingEmployee.rowCount) { await client.query("ROLLBACK"); return { status: "employee_already_linked" as const }; } await client.query("INSERT INTO minutka_private.telegram_sessions(chat_id_digest,user_id_digest,employee_id,thread_id,created_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6)", [chat,user,next.employeeId,next.threadId,next.createdAt,next.updatedAt]); await client.query("COMMIT"); return { status: "claimed" as const, session: next }; } catch (error) { await client.query("ROLLBACK").catch(() => undefined); if ((error as { code?: string }).code === "23505") return { status: "chat_already_linked" as const }; throw new PersistenceError("persistence_unavailable"); } finally { client.release(); } },
  async markConsentAccepted({ identity, employeeId, acceptedAt }) { const result = await pool.query("UPDATE minutka_private.telegram_sessions SET consent_accepted_at=$4, updated_at=$4 WHERE chat_id_digest=$1 AND (user_id_digest IS NOT DISTINCT FROM $2) AND employee_id=$3", [keyedDigest(identity.chatId,pepper),identity.userId ? keyedDigest(identity.userId,pepper) : null,employeeId,acceptedAt]); if (result.rowCount !== 1) throw new Error("telegram session not found"); },
}; }
